name: Connect to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  connect_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSH client
        run: |
          sudo apt-get update
          sudo apt-get -y install openssh-client
      - name: Set permissions for PEM key
        run: |
          echo "${{ secrets.PEM_KEY }}" > key.pem
          chmod 400 key.pem
      - name: Connect to EC2 instance and deploy code
        run: |
          ssh -v -o StrictHostKeyChecking=no -i key.pem ec2-user@3.80.173.163 "
          sudo yum update -y &&
          sudo yum install -y amazon-linux-extras &&
          sudo amazon-linux-extras install -y php8.0 &&
          sudo yum install -y git &&
          sudo yum install -y composer &&
          sudo rm -rf /var/www/html &&
          sudo git clone https://github.com/MohammadNomanAkhtar/second-GA.git /var/www/html &&
          cd /var/www/html &&
          sudo composer install &&
          sudo chown -R ec2-user:ec2-user /var/www/html &&
          sudo chmod -R 755 /var/www/html &&
          sudo systemctl restart httpd"
