name: Connect to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  connect_to_ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSH client
        run: |
          sudo apt-get update
          sudo apt-get -y install openssh-client
          
      - name: Set permissions for PEM key
        run: |
          echo "${{ secrets.PEM_KEY }}" > key.pem
          chmod 400 key.pem
          
      - name: Connect to EC2 instance and deploy code
        run: |
          ssh -v -o StrictHostKeyChecking=no -i key.pem ubuntu@3.80.173.163 << 'EOF'
            sudo apt update -y &&
            sudo apt install -y php git &&
            sudo rm -rf /var/www/html &&
            sudo git clone https://github.com/MohammadNomanAkhtar/second-GA.git /var/www/html &&
            # Set COMPOSER_ALLOW_SUPERUSER to bypass root warning
            export COMPOSER_ALLOW_SUPERUSER=1 &&
            # Check if composer.json exists
            if [ -f /var/www/html/composer.json ]; then
              cd /var/www/html &&
              sudo composer install
            else
              echo "composer.json not found in /var/www/html"
            fi &&
            sudo chown -R ubuntu:ubuntu /var/www/html &&
            sudo chmod -R 755 /var/www/html &&
            sudo systemctl restart nginx
          EOF
